### ISSUE TITLE
Water LinePaths filled when opening in Illustrator

### ISSUE THREAD

**Issue by nathanwoulfe** [mapzen/svg-export#3]
This may be my ignorance in using Illustrator, but if I create a map, export the SVG and open in CS6, some of the water tiles have incorrect fills applied - seems to be tiles where the content is not a polygon, but does not apply to all tiles that are not a polygon.

Tried excluding particular types from the generated SVG, but no luck.

Like I said, probably user error on my part, but would like to get this working correctly.

**Comment by migurski** [comment]
Hi Nathan, thanks for getting in touch. Unfortunately, we're not able to provide support on this code currently, so I'm going to add a note to the front of the repo to make that clear. My colleague @hanbyul-here has a slightly different SVG exporter that she is maintaining on a regular basis, so I invite you to try out her work at https://github.com/hanbyul-here/svg-exporter.

**Comment by nathanwoulfe** [comment]
No worries, I have a feeling it's more me and Illustrator not getting along. Can clean it up manually, but preference is of course to remove the issue. Will check out the other repo too.

**Comment by migurski** [comment]
Yes, please do! We've mostly used the output of the other exporter with Inkscape, but it should do what you need it to do.
